apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      name: mysql
  template:
    metadata:
      labels:
        app: mysql
        name: mysql
    spec:
      containers:
        - name: mysql
          image: lamooon/mysql #can't pull mysql:5.7 since this is M2 Mac
          ports:
          - containerPort: 3306
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
          env:
          - name: MYSQL_USER
            value: MYSQL_USER
          - name: MYSQL_PASSWORD
            value: MYSQL_PASSWORD
          - name: MYSQL_ROOT_PASSWORD
            value: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            value: blog
          - name: MYSQL_HOST
            value: localhost
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      

